version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.9
    ports:
      - '2181:2181'
    environment:
      LOGSPOUT: ignore
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - D:\projects\docs-diff\devops\docker\zookeeper-volume:/var/lib
  kafka:
    image: confluentinc/cp-kafka:7.0.9
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - D:\projects\docs-diff\devops\docker\kafka-volume:/var/lib
