server:
  port: ${PORT:8080}

eureka:
  client:
#    registry-fetch-interval-seconds: 3
    disable-delta: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    instance-id: ${spring.application.name}
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/v1/compare/**

        - id: diff-service
          uri: lb://diff-service
          predicates:
            - Path=/diffs/**

        - id: highlight-service
          uri: lb://highlight-service
          predicates:
            - Path=/highlight/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
