server.port: ${PORT:9000}

testValue: nikhil

spring:
  application.name: compare-service

eureka:
  client:
    disable-delta: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    instance-id: ${spring.application.name}
