server.port: ${PORT:9000}

spring:
  kafka:
    consumer:
      group-id: document-group
  application.name: document-service

eureka:
  client:
    disable-delta: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    instance-id: ${spring.application.name}
